name: CICD Piepline
on: 
  push: 
    branches: main
jobs:
  Git-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository code
        run: actions/checkout@v4
      - name: run a oneline script
        run: echo "This is testing script"
  
